# -*- coding: utf-8 -*-
"""
cst_solver.setup — 类型存根文件
=================================
为 setup 类提供完整的类型提示和函数签名，使 VS Code Pylance 能够正确补全。

此文件由工具自动生成，覆盖所有 Mixin 模块的方法。
"""

from typing import Any, List, Dict, Tuple, Optional, Union

# ============================================================
# CST 项目操作 (ProjectMixin)
# ============================================================
class _ProjectMixin:
    def project_open(self, filename: str) -> None: ...
    def open_project(self, filename: str) -> None: ...
    def project_close(self) -> None: ...
    def close_project(self) -> None: ...
    def close(self) -> None: ...
    def save(self, filename: Optional[str] = None,
             include_results: bool = True,
             allow_overwrite: bool = False) -> None: ...
    def save_as(self, filename: str, include_results: bool = True,
                allow_overwrite: bool = False) -> None: ...
    def new_project(self, project_type: Optional[Any] = None) -> None: ...
    def activate(self) -> None: ...

# ============================================================
# 单位设置 (UnitsMixin)
# ============================================================
class _UnitsMixin:
    def set_units(self, frequency: str = 'GHz', length: str = 'mm',
                  temperature: str = 'Celsius', time: str = 'ns',
                  voltage: str = 'V', current: str = 'A',
                  resistance: str = 'Ohm', inductance: str = 'nH',
                  capacitance: str = 'pF') -> None: ...
    def get_units(self, unit_type: str = 'length') -> str: ...

# ============================================================
# 参数管理 (ParametersMixin)
# ============================================================
class _ParametersMixin:
    def para(self, name: str, value: Union[float, str], log_flag: int = 0,
             expression: str = '') -> None: ...
    def set_parameter(self, name: str, value: Union[float, str], log_flag: int = 0,
                      expression: str = '') -> None: ...
    def paras(self, name: Union[List[str], Dict[str, Any]], value: Optional[list] = None,
              log_flag: int = 0) -> None: ...
    def set_parameters(self, name: Union[List[str], Dict[str, Any]], value: Optional[list] = None,
                       log_flag: int = 0) -> None: ...
    def expression(self, name: str, value: str) -> None: ...
    def set_expression(self, name: str, value: str) -> None: ...
    def freq_limit(self, fmin: Union[float, str], fmax: Union[float, str]) -> None: ...
    def set_frequency_range(self, fmin: Union[float, str], fmax: Union[float, str]) -> None: ...
    def get_parameter(self, name: str) -> Any: ...
    def delete_parameter(self, name: str) -> None: ...
    def rename_parameter(self, old_name: str, new_name: str) -> None: ...

# ============================================================
# 基本体建模 (ModelingPrimitivesMixin)
# ============================================================
class _ModelingPrimitivesMixin:
    def square(self, xmin: Union[float, str], xmax: Union[float, str],
               ymin: Union[float, str], ymax: Union[float, str],
               zmin: Union[float, str], zmax: Union[float, str],
               name: str, component: str = 'component1',
               material: str = 'PEC') -> None: ...
    def create_brick(self, xmin: Union[float, str], xmax: Union[float, str],
                     ymin: Union[float, str], ymax: Union[float, str],
                     zmin: Union[float, str], zmax: Union[float, str],
                     name: str, component: str = 'component1',
                     material: str = 'PEC') -> None: ...
    def cylinder(self, center: list, r: list, h: list, name: str,
                 axis: str = 'z', component: str = 'component1',
                 material: str = 'PEC') -> None: ...
    def create_cylinder(self, center: list, r: list, h: list, name: str,
                        axis: str = 'z', component: str = 'component1',
                        material: str = 'PEC') -> None: ...
    def create_sphere(self, center: list, radius: Union[float, str], name: str,
                      component: str = 'component1', material: str = 'PEC') -> None: ...
    def create_cone(self, bottom_radius: Union[float, str],
                    top_radius: Union[float, str], height: Union[float, str],
                    name: str, center: Optional[list] = None,
                    axis: str = 'z', component: str = 'component1',
                    material: str = 'PEC') -> None: ...
    def create_torus(self, major_radius: Union[float, str],
                     minor_radius: Union[float, str], name: str,
                     center: Optional[list] = None, axis: str = 'z',
                     component: str = 'component1',
                     material: str = 'PEC') -> None: ...
    def create_elliptical_cylinder(self, name: str, x_radius: Union[float, str],
                                   y_radius: Union[float, str],
                                   height: Union[float, str],
                                   center: Optional[list] = None,
                                   axis: str = 'z', component: str = 'component1',
                                   material: str = 'PEC') -> None: ...
    def triangle(self, a: Union[float, str], h: Union[float, str],
                 center: list, theta: list, name: str, curve: str,
                 material: str = 'Silicon (lossy)') -> None: ...
    def create_triangular_prism(self, a: Union[float, str], h: Union[float, str],
                                center: list, theta: list, name: str, curve: str,
                                material: str = 'Silicon (lossy)') -> None: ...
    def hexagon(self, a: Union[float, str], h: Union[float, str],
                center: list, theta: list, name: str,
                curve: str = 'curve1', component: str = 'component1',
                material: str = 'Silicon (lossy)') -> None: ...
    def create_hexagonal_prism(self, a: Union[float, str], h: Union[float, str],
                               center: list, theta: list, name: str,
                               curve: str = 'curve1', component: str = 'component1',
                               material: str = 'Silicon (lossy)') -> None: ...
    def create_wire(self, name: str, start_point: list, end_point: list,
                    radius: Union[float, str], component: str = 'component1',
                    material: str = 'PEC', segments: int = 0) -> None: ...

# ============================================================
# 曲线绘制 (CurvesMixin)
# ============================================================
class _CurvesMixin:
    def polyline(self, data: List[list], name: str = '1',
                 curve: str = 'curve1', log_flag: int = 1) -> str: ...
    def create_polygon(self, data: List[list], name: str = '1',
                       curve: str = 'curve1', log_flag: int = 1) -> str: ...
    def arc(self, center: list, p: list, angle: Union[float, str],
            name: str = "arc1", curve: str = 'curve1',
            orientation: str = 'Counterclockwise',
            log_flag: int = 1) -> str: ...
    def create_arc(self, center: list, p: list, angle: Union[float, str],
                   name: str = "arc1", curve: str = 'curve1',
                   orientation: str = 'Counterclockwise',
                   log_flag: int = 1) -> str: ...
    def ellipse(self, a: Union[float, str], b: Union[float, str],
                center: list, name: str = "arc1",
                curve: str = 'curve1') -> str: ...
    def create_ellipse(self, a: Union[float, str], b: Union[float, str],
                       center: list, name: str = "arc1",
                       curve: str = 'curve1') -> str: ...
    def create_circle(self, center: list, radius: Union[float, str],
                      name: str = "circle1", curve: str = 'curve1') -> None: ...
    def create_line(self, x1: Union[float, str], y1: Union[float, str],
                    z1: Union[float, str], x2: Union[float, str],
                    y2: Union[float, str], z2: Union[float, str],
                    name: str = "line1", curve: str = 'curve1') -> None: ...
    def create_spline(self, points: List[list], name: str = "spline1",
                      curve: str = 'curve1') -> None: ...
    def create_rectangle_curve(self, x1: Union[float, str], y1: Union[float, str],
                               x2: Union[float, str], y2: Union[float, str],
                               name: str = "rect1", curve: str = 'curve1') -> None: ...
    def create_polygon_3d(self, points: List[list], name: str = "poly3d1",
                          curve: str = 'curve1') -> None: ...

# ============================================================
# 曲线操作 (CurveOpsMixin)
# ============================================================
class _CurveOpsMixin:
    def extrude(self, curve: str, name: str, thickness: Union[float, str],
                component: str = 'component1', material: str = 'PEC',
                log_flag: int = 1) -> str: ...
    def extrude_curve(self, curve: str, name: str, thickness: Union[float, str],
                      component: str = 'component1', material: str = 'PEC',
                      log_flag: int = 1) -> str: ...
    def loft_curves(self, curves: List[str], name: str,
                    component: str = 'component1', material: str = 'PEC') -> None: ...
    def sweep_curve(self, path_curve: str, profile_curve: str, name: str,
                    component: str = 'component1', material: str = 'PEC') -> None: ...
    def blend_curve(self, curves: List[str], name: str,
                    curve: str = 'curve1') -> None: ...
    def chamfer_curve(self, curves: List[str], name: str,
                      curve: str = 'curve1') -> None: ...
    def cover_curve(self, closed_curve: str, name: str,
                    component: str = 'component1', material: str = 'PEC') -> None: ...
    def trim_curves(self, curves_to_trim: List[str], trimming_curves: List[str],
                    name: str, curve: str = 'curve1') -> None: ...

# ============================================================
# 布尔运算 (SolidOpsMixin)
# ============================================================
class _SolidOpsMixin:
    def add(self, name1: str, name2: str, component1: str = 'component1',
            component2: str = 'component1') -> None: ...
    def boolean_add(self, name1: str, name2: str, component1: str = 'component1',
                    component2: str = 'component1') -> None: ...
    def subtract(self, name1: str, name2: str, component1: str = 'component1',
                 component2: str = 'component1') -> None: ...
    def boolean_subtract(self, name1: str, name2: str, component1: str = 'component1',
                         component2: str = 'component1') -> None: ...
    def substract(self, name1: str, name2: str, component1: str = 'component1',
                  component2: str = 'component1') -> None:
        """已废弃：历史拼写错误，等价于 subtract()"""
        ...
    def insert(self, name1: str, name2: str, component1: str = 'component1',
               component2: str = 'component1') -> None: ...
    def boolean_insert(self, name1: str, name2: str, component1: str = 'component1',
                       component2: str = 'component1') -> None: ...
    def intersect(self, name1: str, name2: str, component1: str = 'component1',
                  component2: str = 'component1') -> None: ...
    def boolean_intersect(self, name1: str, name2: str, component1: str = 'component1',
                          component2: str = 'component1') -> None: ...
    def boolean_imprint(self, name1: str, name2: str, component1: str = 'component1',
                        component2: str = 'component1') -> None: ...
    def blend(self, r: Union[float, str]) -> None: ...
    def blend_edge(self, r: Union[float, str]) -> None: ...

# ============================================================
# 变换操作 (TransformMixin)
# ============================================================
class _TransformMixin:
    def rotation(self, name: str, angle: list,
                 center: Optional[list] = None, repetition: int = 1,
                 component: str = 'component1', copy: bool = False,
                 unite: bool = False, log_flag: int = 1) -> str: ...
    def rotate(self, name: str, angle: list, center: Optional[list] = None,
               repetition: int = 1, component: str = 'component1',
               copy: bool = False, unite: bool = False,
               log_flag: int = 1) -> str: ...
    def translate(self, name: str, vector: list,
                  component: str = 'component1', repetitions: int = 1,
                  copy: bool = False, unite: bool = False,
                  log_flag: int = 1) -> str: ...
    def mirror(self, name: str, center: list, plane: list,
               component: str = 'component1', object: str = 'Shape',
               copy: bool = False, unite: bool = False) -> None: ...
    def scale(self, name: str, factor: Union[float, str, list],
              center: Optional[list] = None,
              component: str = 'component1') -> None: ...

# ============================================================
# 选取操作 (PickMixin)
# ============================================================
class _PickMixin:
    def pick_edge(self, name: str, id1: Union[int, str], id2: Union[int, str],
                  component: str = 'component1') -> None: ...
    def pick_endpoint(self, name: str, id_val: Union[int, str],
                      component: str = 'component1') -> None: ...
    def pick_face(self, name: str, id_val: Union[int, str],
                  component: str = 'component1') -> None: ...
    def pick_vertex(self, name: str, id_val: Union[int, str],
                    component: str = 'component1') -> None: ...
    def set_edge(self, x1: Union[float, str], y1: Union[float, str],
                 z1: Union[float, str], x2: Union[float, str],
                 y2: Union[float, str], z2: Union[float, str]) -> None: ...
    def pick_clear(self) -> None: ...
    def pick_face_at(self, name: str, x: Union[float, str], y: Union[float, str],
                     z: Union[float, str],
                     component: str = 'component1') -> None: ...
    def pick_edge_at(self, name: str, x: Union[float, str], y: Union[float, str],
                     z: Union[float, str],
                     component: str = 'component1') -> None: ...
    def pick_point_at(self, x: Union[float, str], y: Union[float, str],
                      z: Union[float, str]) -> None: ...
    def get_face_id_from_point(self, name: str, x: Union[float, str],
                               y: Union[float, str], z: Union[float, str],
                               component: str = 'component1') -> Optional[int]: ...
    def get_edge_id_from_point(self, name: str, x: Union[float, str],
                               y: Union[float, str], z: Union[float, str],
                               component: str = 'component1') -> Optional[int]: ...
    def get_picked_count(self, kind: str = 'face') -> Optional[int]: ...
    def pick_face_auto(self, name: str, points: Optional[list] = ...,
                       candidates: Optional[list] = ...,
                       component: str = 'component1') -> Optional[tuple]: ...
class _WCSMixin:
    def wcs_reset(self) -> None: ...
    def reset_wcs(self) -> None: ...
    def wcs_rotate(self, axis: str, angle: Union[float, str]) -> None: ...
    def rotate_wcs(self, axis: str, angle: Union[float, str]) -> None: ...
    def wcs_translate(self, vector: list) -> None: ...
    def translate_wcs(self, vector: list) -> None: ...
    def wcs_align(self, name: str, face_id: int = 0,
                  component: str = 'component1') -> None: ...
    def align_wcs(self, name: str, face_id: int = 0,
                  component: str = 'component1') -> None: ...
    def wcs_set_origin(self, point: list) -> None: ...
    def set_wcs_origin(self, point: list) -> None: ...
    def wcs_rotate_axis(self, from_axis: str, to_axis: str) -> None: ...
    def wcs_store(self, name: str) -> None: ...
    def store_wcs(self, name: str) -> None: ...
    def wcs_restore(self, name: str) -> None: ...
    def restore_wcs(self, name: str) -> None: ...
    def wcs_scale(self, factor_u: float, factor_v: float) -> None: ...
    def scale_wcs(self, factor_u: float, factor_v: float) -> None: ...

# ============================================================
# 面操作 (FaceOpsMixin)
# ============================================================
class _FaceOpsMixin:
    def rotation_face(self, name: str, angle: Union[float, str],
                      component: str = 'component1',
                      material: str = 'Vacuum') -> None: ...
    def rotate_face(self, name: str, angle: Union[float, str],
                    component: str = 'component1',
                    material: str = 'Vacuum') -> None: ...
    def extrude_face(self, name: str, height: Union[float, str],
                     material: str = 'PEC',
                     component: str = 'component1') -> None: ...
    def trace_curve(self, name: str, height: Union[float, str],
                    weight: Union[float, str], material: str = 'PEC',
                    curve: str = 'curve1',
                    component: str = 'component1') -> None: ...

# ============================================================
# 材料与组件 (MaterialMixin)
# ============================================================
class _MaterialMixin:
    def new_material(self, name: str) -> None: ...
    def create_material(self, name: str) -> None: ...
    def create_material_custom(self, name: str, epsilon: Union[float, str],
                               mu: Union[float, str], kappa: Union[float, str],
                               tand: Optional[float] = None,
                               material_type: str = 'Normal') -> None: ...
    def new_component(self, name: str) -> None: ...
    def create_component(self, name: str) -> None: ...
    def new_componet(self, name: str) -> None:
        """已废弃：历史拼写错误，等价于 new_component()"""
        ...
    def create_component(self, name: str) -> None: ...
    def rename(self, old: str, new: str, type: str = 'Solid') -> None: ...
    def rename_solid(self, old: str, new: str) -> None: ...
    def rename_component(self, old: str, new: str) -> None: ...
    def change_component(self, model: str, component: str) -> None: ...
    def change_material(self, model: str, material: str) -> None: ...
    def list_library_materials(self) -> List[str]: ...
    def load_material_from_file(self, filepath: str,
                                name: Optional[str] = None) -> bool: ...

# ============================================================
# 端口设置 (PortMixin)
# ============================================================
class _PortMixin:
    def add_port(self, id_val: Union[int, str], orientation: str = 'positive',
                 shield: str = '') -> None: ...
    def create_waveguide_port(self, id_val: Union[int, str],
                              orientation: str = 'positive',
                              shield: str = '') -> None: ...
    def create_waveguide_port_free(self, id_val: Union[int, str],
                                   xrange: Optional[tuple] = None,
                                   yrange: Optional[tuple] = None,
                                   zrange: Optional[tuple] = None,
                                   orientation: str = 'positive',
                                   shield: str = '') -> None: ...
    # 注：discrete_port / create_discrete_face_port 的旧拼写关键字
    #     invertdrection 仍可通过 **legacy_kwargs 传入，已废弃
    def discrete_port(self, r0: Union[float, str], id_val: Union[int, str],
                      fold: str = '', invert_direction: bool = False,
                      **legacy_kwargs) -> None: ...
    def create_discrete_face_port(self, r0: Union[float, str],
                                  id_val: Union[int, str], fold: str = '',
                                  invert_direction: bool = False,
                                  **legacy_kwargs) -> None: ...
    def create_discrete_port(self, id_val: Union[int, str], p1: list, p2: list,
                             impedance: Union[float, str] = 50,
                             label: str = '', folder: str = '') -> None: ...
    def lumped_element(self, id_val: Union[int, str],
                       r: Union[float, str]) -> None: ...
    def create_lumped_element(self, id_val: Union[int, str],
                              r: Union[float, str] = 0,
                              l: Union[float, str] = 0,
                              c: Union[float, str] = 0,
                              p1: Optional[list] = None,
                              p2: Optional[list] = None,
                              element_type: str = 'RLCSerial') -> None: ...
    def create_floquet_port(self, id_val: Union[int, str],
                            number_of_modes: int = 2,
                            label: str = '', folder: str = '') -> None: ...
    def create_cable_port(self, id_val: Union[int, str], label: str = '',
                          impedance: float = 50) -> None: ...

# ============================================================
# 激励源 (SourceMixin)
# ============================================================
class _SourceMixin:
    def create_plane_wave(self, name: str, direction: list, polarization: list,
                          frequency: Optional[float] = None,
                          phase: float = 0) -> None: ...
    def create_current_port(self, id_val: Union[int, str], p1: list, p2: list,
                            current: float = 1.0, label: str = '') -> None: ...
    def create_coil(self, name: str, turns: int, radius: float,
                    current: float = 1.0, center: Optional[list] = None,
                    axis: str = 'z') -> None: ...
    def create_voltage_wire(self, id_val: Union[int, str], p1: list, p2: list,
                            voltage: float = 1.0) -> None: ...
    def create_charge(self, name: str, charge_value: float,
                      center: Optional[list] = None) -> None: ...
    def create_current_path(self, name: str, current: float = 1.0,
                            component: str = 'component1') -> None: ...
    def create_magnet(self, name: str, coercivity: float, remanence: float,
                      axis: str = 'z') -> None: ...
    def create_field_source(self, name: str, filename: str) -> None: ...
    def create_predefined_field(self, name: str, field_type: str = 'E',
                                amplitude: str = '1.0') -> None: ...
    def create_farfield_source(self, name: str, source_file: str,
                               polarization: str = 'Theta',
                               distance: float = 1.0) -> None: ...
    def create_time_signal(self, name: str, signal_type: str = 'Gaussian',
                           amplitude: float = 1.0, center_time: float = 0.0,
                           width: float = 1.0, frequency: float = 1.0) -> None: ...

# ============================================================
# 监视器 (MonitorMixin)
# ============================================================
class _MonitorMixin:
    def define_monitor(self, name: str, freq: list) -> None: ...
    def create_field_monitor(self, monitor_type: str,
                             frequencies: list) -> None: ...
    def create_probe(self, name: str, position: list,
                     frequency: Optional[float] = None,
                     field_type: str = 'E') -> None: ...

# ============================================================
# 边界条件 (BoundaryMixin)
# ============================================================
class _BoundaryMixin:
    def boundary(self, xmax: str = 'expanded open', xmin: str = 'expanded open',
                 ymax: str = 'expanded open', ymin: str = 'expanded open',
                 zmax: str = 'expanded open', zmin: str = 'expanded open',
                 Xsymmetry: str = 'none', Ysymmetry: str = 'none',
                 Zsymmetry: str = 'none', ApplyInAllDirections: bool = False,
                 OpenAddSpaceFactor: float = 0.5) -> None: ...
    def set_boundary(self, **kwargs) -> None: ...
    def set_background(self, material: str = 'Vacuum',
                       xmin_space: float = 0, xmax_space: float = 0,
                       ymin_space: float = 0, ymax_space: float = 0,
                       zmin_space: float = 0, zmax_space: float = 0,
                       background_type: str = 'Normal',
                       apply_in_all_directions: bool = False) -> None: ...
    def set_layer_stacking(self, direction: str = 'z',
                           stack_type: str = 'Default',
                           periodicity: Optional[list] = None) -> None: ...

# ============================================================
# 求解器 (SolverMixin)
# ============================================================
class _SolverMixin:
    def T_solver(self) -> None: ...
    def configure_time_solver(self) -> None: ...
    def set_steady_state_limit(self, db: Union[float, str] = '-30') -> None: ...
    def set_parallel_threads(self, threads: Union[int, str] = 8,
                             enable: bool = True) -> None: ...
    def set_mesh_adaption(self, enable: bool = False) -> None: ...
    def set_gpu_acceleration(self, gpus: Union[int, str] = 1,
                             enable: bool = True) -> None: ...
    def run(self) -> None: ...
    def update(self) -> None: ...
    def configure_fd_solver(self, accuracy: str = '-60') -> None: ...
    def configure_eigenmode_solver(self, n_modes: int = 3,
                                   frequency: str = '1.0') -> None: ...
    def exclude_simulation(self, name: str, component: str = 'component1') -> None: ...
    def exclude_from_simulation(self, name: str,
                                component: str = 'component1') -> None: ...
    def configure_ie_solver(self, accuracy: str = '-30',
                            use_fast_frequency_sweep: bool = True) -> None: ...
    def configure_asymptotic_solver(self, accuracy: str = '-30') -> None: ...
    def configure_parameter_sweep(self, sequence: str = '',
                                  start: bool = True) -> None: ...
    def add_parameter_sweep_sequence(self, sequence_name: str = 'sweep1') -> None: ...
    def add_sweep_parameter_samples(self, seq_name: str, param_name: str,
                                    lower_bound: float, upper_bound: float,
                                    num_steps: int) -> None: ...
    def start_parameter_sweep(self) -> None: ...
    def configure_optimizer(self, goal: str = '',
                            max_iterations: str = '100') -> None: ...
    def add_optimizer_goal(self, name: str, goal_type: str, operator: str,
                           target: float, weight: float = 1.0) -> None: ...
    def add_optimizer_parameter(self, param_name: str, min_val: float,
                                max_val: float) -> None: ...
    def start_optimizer(self) -> None: ...
    def configure_eigenmode_solver_ext(self, n_modes: int = 3,
                                       frequency: str = '1.0',
                                       method: str = 'AKS',
                                       mesh_type: str = 'Tetrahedral') -> None: ...
    def configure_ie_solver_ext(self, accuracy: str = '-30',
                                use_fast_frequency_sweep: bool = True,
                                mesh_type: str = 'Tetrahedral',
                                max_frequency_samples: int = 100) -> None: ...
    def set_solver_parameter(self, **kwargs) -> None: ...
    def set_max_iterations(self, max_iter: int) -> None: ...
    def set_residual(self, residual: float) -> None: ...

# ============================================================
# 网格设置 (MeshMixin)
# ============================================================
class _MeshMixin:
    def set_mesh_properties(self, max_cell: Optional[float] = None,
                            min_cell: Optional[float] = None,
                            lines_per_wavelength: int = 10,
                            mesh_type: str = 'PBA') -> None: ...
    def configure_mesh_adaption(self, max_passes: int = 6,
                                max_refinement: float = 1e-6,
                                adaptive_tolerance: float = 0.01) -> None: ...
    def set_mesh_auto(self, lines_per_wavelength: int = 10,
                      lower_mesh_limit: int = 10, mesh_type: str = 'PBA',
                      ratio_limit: int = 10,
                      smallest_mesh_step: str = '1e-6') -> None: ...
    def set_mesh_settings(self, **kwargs) -> None: ...
    def set_mesh_shape(self, shape: str = 'hexahedral') -> None: ...
    def set_mesh_region(self, name: str, priority: int = 0,
                        xmin: Optional[float] = None,
                        xmax: Optional[float] = None,
                        ymin: Optional[float] = None,
                        ymax: Optional[float] = None,
                        zmin: Optional[float] = None,
                        zmax: Optional[float] = None,
                        mesh_type: Optional[str] = None,
                        step: Optional[float] = None) -> None: ...

# ============================================================
# 导入导出 (IOMixin)
# ============================================================
class _IOMixin:
    def import_subproject(self, filename: str, subproject_name: str,
                          scale_factor: str = '0.001', version: str = '15.0',
                          portname_map: str = '',
                          import_to_active_coordinate_system: str = 'True',
                          curves: str = 'True', wires: str = 'True',
                          solid_wires_as_solids: str = 'False',
                          import_sources: str = 'False',
                          import_sensitivity_information: str = 'False') -> None: ...
    def sat_import(self, filename: str, tpn: str = 'True') -> None: ...
    def import_sat(self, filename: str, tpn: str = 'True') -> None: ...
    def dxf_import(self, filename: str, add: str = 'True',
                   HealSelfIntersections: str = 'False',
                   component: Union[str, list] = 'component2',
                   material: Union[str, list] = 'Silicon (lossy)',
                   height: Union[str, list] = '0') -> None: ...
    def import_dxf(self, filename: str, add: str = 'True',
                   HealSelfIntersections: str = 'False',
                   component: Union[str, list] = 'component2',
                   material: Union[str, list] = 'Silicon (lossy)',
                   height: Union[str, list] = '0') -> None: ...
    def import_step(self, filename: str, unit: str = 'mm') -> None: ...
    def import_iges(self, filename: str, unit: str = 'mm') -> None: ...
    def import_stl(self, filename: str, unit: str = 'mm') -> None: ...
    def field_export(self, tree_item: str, save_path: str,
                     mode: str = 'FixedWidth', step: int = -1) -> None: ...
    def export_field(self, tree_item: str, save_path: str,
                     mode: str = 'FixedWidth', step: int = -1) -> None: ...
    def pattern_export(self, tree_item: str, save_path: str,
                       plottype: str = '3d', plotmode: str = 'realized gain',
                       step: int = -1) -> None: ...
    def export_pattern(self, tree_item: str, save_path: str,
                       plottype: str = '3d', plotmode: str = 'realized gain',
                       step: int = -1) -> None: ...
    def patten_export(self, tree_item: str, save_path: str,
                      plottype: str = '3d', plotmode: str = 'realized gain',
                      step: int = -1) -> None:
        """已废弃：历史拼写错误，等价于 pattern_export()"""
        ...
    def export_data(self, tree_item: str, save_path: str) -> None: ...
    def export_to_ascii(self, tree_item: str, save_path: str) -> None: ...

# ============================================================
# 后处理 (PostProcMixin)
# ============================================================
class _PostProcMixin:
    def calculate_q_factor(self, s_param_path: str = 'S-Parameters\\S1,1',
                           method: str = '3dB') -> None: ...
    def combine_results(self, operation: str, result_paths: List[str],
                        new_name: str) -> None: ...
    def calculate_sar(self, mass_density: str = '1000',
                      averaging_method: str = '1g') -> None: ...
    def post_process_1d(self, operation: str, result_path: str,
                        new_name: str = '') -> None: ...
    def post_process_apply_to(self, apply_target: str = 'S-parameter') -> None: ...
    def post_process_add_operation(self, operation_type: str) -> None: ...
    def post_process_run(self) -> None: ...

# ============================================================
# 远场后处理 (FarfieldMixin)
# ============================================================
class _FarfieldMixin:
    @property
    def farfield_plot(self) -> Any: ...
    def set_farfield_plot(self, plottype: str = '3d',
                          plotmode: str = 'realized gain',
                          frequency: Optional[float] = None) -> None: ...
    def compute_farfield_array(self, array_type: str = 'rectangular',
                               element_count: tuple = (2, 2),
                               spacing: tuple = (0.5, 0.5)) -> None: ...

# ============================================================
# 绘图控制 (PlotMixin)
# ============================================================
class _PlotMixin:
    def plot_reset(self) -> None: ...
    def reset_plot(self) -> None: ...
    def plot_1d(self, tree_path: str) -> None: ...
    def plot_2d3d(self, tree_path: str) -> None: ...
    def scalar_plot_2d(self, tree_path: str, component: str = '',
                       frequency: Optional[float] = None) -> None: ...
    def scalar_plot_3d(self, tree_path: str, component: str = 'Abs',
                       frequency: Optional[float] = None) -> None: ...
    def vector_plot_2d(self, tree_path: str,
                       frequency: Optional[float] = None) -> None: ...
    def vector_plot_3d(self, tree_path: str,
                       frequency: Optional[float] = None) -> None: ...
    def farfield_plot_polar(self, frequency: Optional[float] = None,
                            mode: str = 'directivity',
                            theta_start: float = 0, theta_stop: float = 360,
                            theta_step: float = 1) -> None: ...
    def farfield_plot_cartesian(self, frequency: Optional[float] = None,
                                mode: str = 'directivity') -> None: ...
    def plot_set_properties(self, properties: dict) -> None: ...
    def plot_animate(self, tree_path: str, parameter: str,
                     start: float, stop: float, step: float) -> None: ...
    def plot_delete_all(self) -> None: ...

# ============================================================
# 结果导出 (ExportMixin)
# ============================================================
class _ExportMixin:
    def export_result_1d(self, tree_path: str, save_path: str) -> None: ...
    def export_result_2d3d(self, tree_path: str, save_path: str,
                           mode: str = 'FixedWidth', step: int = -1,
                           usesubvolume: bool = False,
                           setsubvolume: Optional[list] = None) -> None: ...

# ============================================================
# setup 主类 — 聚合所有功能的类型声明
# ============================================================
class setup(
    _ProjectMixin,
    _UnitsMixin,
    _ParametersMixin,
    _ModelingPrimitivesMixin,
    _CurvesMixin,
    _CurveOpsMixin,
    _WCSMixin,
    _SolidOpsMixin,
    _TransformMixin,
    _PickMixin,
    _FaceOpsMixin,
    _MaterialMixin,
    _PortMixin,
    _SourceMixin,
    _MonitorMixin,
    _BoundaryMixin,
    _SolverMixin,
    _MeshMixin,
    _IOMixin,
    _PostProcMixin,
    _FarfieldMixin,
    _PlotMixin,
    _ExportMixin,
):
    """
    CST 电磁仿真自动化操作核心类
    ==============================
    通过多继承聚合所有功能模块。

    用法:
        >>> app = setup("example.cst")
        >>> app.create_brick(0, 10, 0, 10, 0, 2, "substrate")
        >>> app.set_frequency_range(1, 10)
        >>> app.create_waveguide_port(1)
        >>> app.run()
        >>> app.close()
    """

    def __init__(self, filename: Optional[str] = None) -> None: ...
    def _open_and_activate(self, filename: str) -> None: ...
    def open(self, filename: str) -> None: ...
    def __enter__(self) -> 'setup': ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
